import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header />  */}
        <header className="flex py-4 bg-gray-900 text-white w-full items-center justify-center border-b">
          <div className="flex items-center">
            <p className="text-lg font-semibold leading-none tracking-tight">
              Multi Step Form Validation
            </p>
          </div>
        </header>
        
       <div className=" max-w-7xl mx-auto">{children}</div>
        {/* <Footer /> */}
        <footer className="flex py-4 w-full items-center justify-center bg-gray-900 text-white border-t">
          <div className="flex items-center">
            <p className="text-sm text-muted-foreground">
              &copy; {new Date().getFullYear()} our Company
            </p>
          </div>
        </footer> 
      </body>
    </html>
  );
}
